apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- ingress.yml
- persistent-volume-claim.yml
- service.yml
commonLabels:
  app.kubernetes.io/name: home-assistant
  app: home-assistant
configMapGenerator:
- name: home-assistant-config
  literals:
  - TZ="UTC"
